#!/usr/bin/env python3
"""
Cleanup utility for HSPICE test files
Removes all test_*.* files generated by the verification script
"""

import glob
from pathlib import Path

def cleanup_test_files():
    """Remove all test files generated by verification"""
    
    # All possible test file patterns
    patterns = [
        'test_*.sp',
        'test_*.lis',
        'test_*.ic',
        'test_*.ic0',
        'test_*.st0',
        'test_*.tr0',
        'test_*.pa0',
        'test_*.mt0',
        'test_*.ms0',
        'test_*.sw0',
        'test_*.ac0',
        'test_*.measure',
        'test_*.log',
        'test_*.out'
    ]
    
    all_files = []
    for pattern in patterns:
        all_files.extend(glob.glob(pattern))
    
    if not all_files:
        print("✅ No test files found - directory is clean!")
        return
    
    print(f"\n{'='*60}")
    print(f"Found {len(all_files)} test file(s)")
    print(f"{'='*60}")
    
    # Group by extension for summary
    by_ext = {}
    for f in all_files:
        ext = Path(f).suffix
        by_ext[ext] = by_ext.get(ext, 0) + 1
    
    for ext, count in sorted(by_ext.items()):
        print(f"  {ext:10s}: {count:4d} files")
    
    print(f"{'='*60}\n")
    
    # Ask for confirmation
    response = input("Delete all these files? (y/n): ")
    
    if response.lower() == 'y':
        deleted = 0
        failed = 0
        
        for f in all_files:
            try:
                Path(f).unlink()
                deleted += 1
            except Exception as e:
                print(f"⚠️  Could not delete {f}: {e}")
                failed += 1
        
        print(f"\n✅ Deleted {deleted} files")
        if failed > 0:
            print(f"⚠️  Failed to delete {failed} files")
    else:
        print("\n❌ Cleanup cancelled")

if __name__ == '__main__':
    cleanup_test_files()